//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6DbFirstTeke
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eredmenyek
    {
        public int Sorsz { get; set; }
        public int Teli { get; set; }
        public int Tarolas { get; set; }
        public int Ures { get; set; }
        public int VersenyzoRajtszam { get; set; }
    
        public virtual Versenyzok Versenyzok { get; set; }
    }
}
