//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6ModelFirstTeke
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TekeDbModelContainer : DbContext
    {
        public TekeDbModelContainer()
            : base("name=TekeDbModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Egyesulet> Egyesuletek { get; set; }
        public virtual DbSet<Versenyzo> Versenyzok { get; set; }
        public virtual DbSet<Eredmeny> Eredmenyek { get; set; }
    }
}
