//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6ModelFirstTeke
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versenyzo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Versenyzo()
        {
            this.Eredmenyek = new HashSet<Eredmeny>();
        }
    
        public int Rajtszam { get; set; }
        public string Nev { get; set; }
        public string Korcsop { get; set; }
        public int EgyesuletId { get; set; }
    
        public virtual Egyesulet Egyesulet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eredmeny> Eredmenyek { get; set; }
    }
}
